---
# ---- Default values to be merged into tasks ----

env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  PIP_CACHE_DIR: ${CIRRUS_WORKING_DIR}/.cache/pip
  PRE_COMMIT_HOME: ${CIRRUS_WORKING_DIR}/.cache/pre-commit
  # Coveralls configuration
  CI_NAME: cirrus-ci
  CI_BRANCH: ${CIRRUS_BRANCH}
  CI_PULL_REQUEST: ${CIRRUS_PR}
  CI_BUILD_NUMBER: ${CIRRUS_BUILD_ID}
  CI_BUILD_URL: https://cirrus-ci.com/build/${CIRRUS_BUILD_ID}
  COVERALLS_PARALLEL: "true"
  COVERALLS_FLAG_NAME: ${CIRRUS_TASK_NAME}

# ---- Templates ----

.task_template: &task-template
  debug_information_script:
    - echo "$(which python) -- $(python -VV)"
    - echo "$(which pip) -- $(pip -VV)"
    - python -c 'import os, sys; print(os.name, sys.platform, getattr(sys, "abiflags", None))'
  prepare_script:  # avoid git failing with setuptools-scm
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
  pip_cache:
    folder: "${CIRRUS_WORKING_DIR}/.cache/pip"
    fingerprint_script: echo "${CIRRUS_OS}-${CIRRUS_TASK_NAME}"
    reupload_on_changes: true
  pre_commit_cache:
    folder: "${CIRRUS_WORKING_DIR}/.cache/pre-commit"
    fingerprint_script: echo "${CIRRUS_OS}-${CIRRUS_TASK_NAME}" | cat - .pre-commit-config.yaml
    reupload_on_changes: true

.test_template: &test-template
  # Requires pip, tox, and pipx to be installed via OS/pip
  alias: test
  depends_on: [build]
  <<: *task-template
  dist_cache: {folder: dist, fingerprint_script: echo $CIRRUS_BUILD_ID}  # download
  test_script: >
    tox --installpkg dist/*.whl -e all --
    -n 5 --randomly-seed=42 -rfEx --durations 10 --color yes
  submit_coverage_script:
    - pipx run coverage xml -o coverage.xml
    - pipx run coveralls --submit coverage.xml

# Deep clone script for POSIX environments (required for setuptools-scm)
.clone_script: &clone |
  if [ -z "$CIRRUS_PR" ]; then
    git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
    git reset --hard $CIRRUS_CHANGE_IN_REPO
  else
    git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
    git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
    git reset --hard $CIRRUS_CHANGE_IN_REPO
  fi

# ---- CI Pipeline ----

build_task:
  name: build (Linux - 3.10)
  alias: build
  container: {image: "python:3.10-bullseye"}
  clone_script: *clone
  dist_cache:  # build once and upload to be used by other tasks
    folder: dist
    fingerprint_script: echo $CIRRUS_BUILD_ID
    reupload_on_changes: true
  <<: *task-template
  install_script: pip install tox
  build_script: tox -e clean,build

check_task:
  name: check (Linux - 3.10)
  alias: check
  depends_on: [build]
  container: {image: "python:3.10-bullseye"}  # most recent => better types
  dist_cache: {folder: dist, fingerprint_script: echo $CIRRUS_BUILD_ID}  # download
  <<: *task-template
  install_script: pip install tox
  check_script: tox --installpkg dist/*.whl -e lint,typecheck

linux_task:
  matrix:
    - name: test (Linux - 3.6)
      container: {image: "python:3.6-bullseye"}
      allow_failures: true  # EoL
    - name: test (Linux - 3.7)
      container: {image: "python:3.7-bullseye"}
    - name: test (Linux - 3.8)
      container: {image: "python:3.8-bullseye"}
    - name: test (Linux - 3.9)
      container: {image: "python:3.9-bullseye"}
    - name: test (Linux - 3.10)
      container: {image: "python:3.10-bullseye"}
    - name: test (Linux - 3.11)
      container: {image: "python:3.11-rc-bullseye"}
      allow_failures: true  # Experimental
  install_script:
    - python -m pip install --upgrade pip tox pipx
  <<: *test-template

mamba_task:
  name: test (Linux - mambaforge)
  container: {image: "condaforge/mambaforge"}
  install_script:  # Overwrite template
    - mamba install -y pip tox pipx
  <<: *test-template

macos_task:
  name: test (macOS - brew)
  macos_instance: {image: "big-sur-xcode"}
  brew_cache: {folder: "$HOME/Library/Caches/Homebrew"}
  install_script: brew install python tox pipx
  env:
    PATH: "/usr/local/opt/python/libexec/bin:${PATH}"
  <<: *test-template

freebsd_task:
  name: test (freebsd - 3.8)
  freebsd_instance: {image_family: freebsd-13-0}
  install_script:
    - pkg remove -y python lang/python
    - pkg install -y git python38 py38-pip py38-gdbm py38-sqlite3 py38-tox py38-pipx vim
    - ln -s /usr/local/bin/python3.8 /usr/local/bin/python
  <<: *test-template

windows_task:
  name: test (Windows - 3.9.10)
  windows_container:
    image: "cirrusci/windowsservercore:2019"
    os_version: 2019
  env:
    CIRRUS_SHELL: bash
    PATH: /c/Python39:/c/Python39/Scripts:/c/tools:${PATH}
  install_script:
    # Activate long file paths to avoid some errors
    - ps: New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
    - choco install -y --no-progress python3 --version=3.9.10 --params "/NoLockdown"
    - choco install -y --no-progress vim
    - pip install --upgrade certifi
    - python -m pip install -U pip tox pipx
  <<: *test-template

finalize_task:
  container: {image: "python:3.10-bullseye"}
  depends_on: [test]
  <<: *task-template
  install_script: pip install coveralls
  finalize_coverage_script: coveralls --finish

linkcheck_task:
  name: linkcheck (Linux - 3.10)
  container: {image: "python:3.10-bullseye"}
  depends_on: [finalize]
  allow_failures: true
  dist_cache: {folder: dist, fingerprint_script: echo $CIRRUS_BUILD_ID}  # download
  <<: *task-template
  install_script: pip install tox
  linkcheck_script: tox --installpkg dist/*.whl -e linkcheck -- -q

# # The following task is already covered by a GitHub Action,
# # (commented to avoid errors when publishing duplicated packages to PyPI)
# publish_task:
#   name: publish (Linux - 3.10)
#   container: {image: "python:3.10-bullseye"}
#   depends_on: [check, build, test]
#   only_if: $CIRRUS_TAG =~ 'v\d.*' && $CIRRUS_USER_PERMISSION == "admin"
#   <<: *task-template
#   dist_cache: {folder: dist, fingerprint_script: echo $CIRRUS_BUILD_ID}  # download
#   env:
#     TWINE_REPOSITORY: pypi
#     TWINE_USERNAME: __token__
#     TWINE_PASSWORD: $PYPI_TOKEN
#     # See: https://cirrus-ci.org/guide/writing-tasks/#encrypted-variables
#   install_script: pip install tox
#   publish_script:
#     - ls dist/*
#     - tox -e publish
