# Environment file for ReadTheDocs, check .readthedocs.yml
name: pyscaffold
channels:
  - defaults
dependencies:
  - python=3.8
  - sphinx>=3.2.1
  - setuptools>=38.3
  - pip
  - pip:
      # to build the module reference correctly, make sure every external package
      # under `install_requires` in `setup.cfg` is also listed here!
      - configupdater
      - appdirs
      - tomlkit
      - setuptools_scm
      - packaging
